spring.application.name=smart_stylist

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_stylist
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT: This will create the database if it doesn't exist (if you add this dependency)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.web.resources.static-locations=file:uploads/

# Google Gemini API Configuration
gemini.api.key=AIzaSyDeMuLf_FCu8Epy1GTfl6Ukq6bapfnvDWQ
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent


# Logging
logging.level.com.example.smart_stylist=DEBUG
logging.level.org.springframework.web=DEBUG


# HUGGING FACE
huggingface.api.key=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
huggingface.text.model=openai/gpt-oss-120b
huggingface.image.model=google/vit-base-patch16-224
huggingface.api.router=https://router.huggingface.co/v1/chat/completions

# HTTP 
huggingface.http.connectTimeout=60
huggingface.http.readTimeout=60
huggingface.http.writeTimeout=60

# Retry
huggingface.retry.delay=3000
huggingface.retry.maxAttempts=3